import{a as y,S as L,i as l}from"./assets/vendor-CRCB-GUD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const g=(s,t)=>{const r={params:{key:"45683137-9da9ef345b4290ae910ded200",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};return y.get("https://pixabay.com/api/",r)},m=s=>`<li class="gallery-card">
    <a href="${s.largeImageURL}"><img src="${s.previewURL}" alt="" title="" class="gallery-img"/></a>
    <div class="card-info">
    <ul class="info-text">
    <li>Likes<span>${s.likes}</span></li>
    <li>Views<span>${s.views}</span></li>
    <li>Comments<span>${s.comments}</span></li>
    <li>Downloads<span>${s.downloads}</span></li>
    </ul>
</div></li>`,c=document.querySelector(".js-search-form"),n=document.querySelector(".js-gallery"),d=document.querySelector(".loader"),p=document.querySelector(".js-load-more");let a=1,h=0;const f=new L(".gallery a",{captions:!0,captionDelay:250,captionPosition:"bottom"}),v=async s=>{try{s.preventDefault();const t=c.elements.user_query.value;a=1,d.classList.toggle("is-hidden");const r=await g(t,a);if(d.classList.toggle("is-hidden"),r.data.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),n.innerHTML="",c.reset();return}const i=r.data.hits.map(e=>m(e)).join("");n.innerHTML=i,f.refresh(),h=n.getBoundingClientRect().height,a*15>=r.data.totalHits||p.classList.remove("is-hidden")}catch(t){l.error({message:t.message,position:"topRight"}),console.log(t)}},b=async s=>{try{a++;const t=c.elements.user_query.value;d.classList.toggle("is-hidden");const r=await g(t,a);d.classList.toggle("is-hidden");const i=r.data.hits.map(e=>m(e)).join("");n.insertAdjacentHTML("beforeend",i),f.refresh(),a*15>=r.data.totalHits&&(p.classList.add("is-hidden"),l.show({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),scrollBy({top:h*2,behavior:"smooth"})}catch(t){l.error({message:t.message,position:"topRight"}),console.log(t)}};c.addEventListener("submit",v);p.addEventListener("click",b);
//# sourceMappingURL=index.js.map
